/**
 * Export Meeting Transcript Utility
 * Formats in-memory transcript logs & chat records and triggers browser download as a .txt file.
 */
export function downloadMeetingTranscript(roomId, transcriptLogs = [], chatMessages = []) {
  const dateStr = new Date().toLocaleDateString();
  const timeStr = new Date().toLocaleTimeString();

  const header = `===================================================\n` +
                 `📄 SL-MEET MEETING TRANSCRIPT & ASL RECORD\n` +
                 `Room ID: ${roomId}\n` +
                 `Date: ${dateStr} | Time: ${timeStr}\n` +
                 `===================================================\n\n`;

  // Sort & Merge ASL sentence logs and text chat messages chronologically
  const combinedEntries = [
    ...transcriptLogs.map((log) => ({
      timestamp: log.timestamp || Date.now(),
      timeFormatted: log.time || new Date(log.timestamp || Date.now()).toLocaleTimeString(),
      sender: log.sender || 'Participant',
      type: 'ASL Subtitle',
      text: log.text,
    })),
    ...chatMessages
      .filter((msg) => msg.type !== 'system')
      .map((msg) => ({
        timestamp: msg.timestamp || Date.now(),
        timeFormatted: new Date(msg.timestamp || Date.now()).toLocaleTimeString(),
        sender: msg.senderName || 'Participant',
        type: 'Text Chat',
        text: msg.text,
      })),
  ].sort((a, b) => a.timestamp - b.timestamp);

  const body = combinedEntries.length === 0
    ? 'No ASL sentences or chat messages recorded in this call.\n'
    : combinedEntries
        .map((entry) => `[${entry.timeFormatted}] ${entry.sender} (${entry.type}): ${entry.text}`)
        .join('\n');

  const footer = `\n===================================================\n` +
                 `Generated by SL-Meet AI Platform\n` +
                 `===================================================\n`;

  const fullContent = header + body + footer;
  const blob = new Blob([fullContent], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = `SL-Meet-Transcript-${roomId}-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
